---
# Section: chronograf service
apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: chronograf
  labels:
    component: chronograf
    app: chronograf
spec:
  ports:
  - port: 80
    targetPort: 8888
    name: server
  selector:
    component: chronograf
---
# Section: chronograf deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logging
  name: chronograf
  labels:
    app: chronograf
    component: chronograf
spec:
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      component: chronograf
  replicas: 1
  template:
    metadata:
      name: chronograf
      labels:
        app: chronograf
        component: chronograf
    spec:
      containers:
      - name: chronograf
        image: quay.io/influxdb/chronograf:nightly
        env:
          - name: RESOURCES_PATH
            value: "/usr/share/chronograf/resources"
          - name: LOG_LEVEL
            value: "error"
        ports:
          - containerPort: 8888
            name: server
        volumeMounts:
          - name: data
            mountPath: /var/lib/chronograf
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: chronograf
---
# Section: chronograf persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: logging
  name: chronograf
  labels:
    app: chronograf
    component: chronograf
spec:
  storageClassName: "nfs-client"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
